TARGET=mod_mruby.c ap_mrb_request.c ap_mrb_string.c ap_mrb_utils.c

APXS=apxs

INC=-I. -I../mruby/src -I../mruby/include
APACHE_ROOT=c:/progra~1/apache~1/apache2.2
LIB=-lm ../mruby/lib/libmruby.a -llibapr-1 -llibaprutil-1 -llibhttpd -lws2_32
DEF=-DAPR_DECLARE_EXPORT

all: mod_mruby.so

mod_mruby.so: $(TARGET)
	$(APXS) -c $(DEF) $(INC) $(TARGET) $(LIB)

install: all
	$(APXS) -i -a -n "mruby" .libs/mod_mruby.so

clean:
	-rm -rf .libs *.o *.so *.lo *.la *.slo *.loT
